name: Run API HUB Tests on Merge to Main

on:
  pull_request:
    types: [closed]

jobs:
  run-semea-accounts:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Run SEMEA Accounts Test Suite
        run: |
          curl -X POST http://172.26.10.147:8080/job/SEMEA_Accounts_TestSuite/build \
            --user dev-test:11cae3408b48d59a94cde4275b0ecb475a

  run-cas-create-reseller:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Run CAS Create Reseller Test Suite
        run: |
          curl -X POST http://172.26.10.147:8080/job/CAS_CreateReseller_TestSuite/build \
            --user dev-test:11cae3408b48d59a94cde4275b0ecb475a
